<b>What does Pandas stand for?</b><br>
Pandas stands for "Panel Data". It is multi-dimensional data.

<b>What are the 2 collections used in Pandas?</b><br>
Series and DataFrame are two main collections in pandas.

<b>Name 4 things Pandas can do for us.</b><br>
We can load data file, know the dimension and shape of the data, understand the data through summary() and merge multiple dataframes.

<b>To permanently sort a DataFrame, which keyword should one use with the df.sort() method?</b><br>
inplace() is used to sort dataframe.

<b>What is a CSV?</b><br>
CSV is comma separated file. It is structured data format.

<b>When cleaning data what values do we not like in our data?</b><br>
Null values and extreme values.

In [14]:
# Import NumPy, use one of the NumPy methods and create an array with a shape of (2, 3, 2). You can use the reshape method -- .reshape()
import numpy as np
arr = np.arange(12).reshape(2, 3, 2)
print("Array with shape (2, 3, 2):\n", arr)

Array with shape (2, 3, 2):
 [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [7]:
# Use NumPy .linspace() to create an array with 6 linearly spaced values between 0 and 20
ln_arr = np.linspace(0, 20, 6)
print("Array with 6 linearly spaced values between 0 and 20:\n", ln_arr)

Array with 6 linearly spaced values between 0 and 20:
 [ 0.  4.  8. 12. 16. 20.]


In [9]:
# Make a Deep Copy of the above array
dc_arr= np.copy(ln_arr)
print("Deep Copy arr is ",dc_arr)

Deep Copy arr is  [ 0.  4.  8. 12. 16. 20.]


In [11]:
# Concatenate these 3 arrays into a new array named 'newArray'...
# ([[25, 16]])
# ([[11, 2], [13, 4]])
# ([[7, 81], [5, 6], [11, 12]])

ct_arr = np.concatenate([
    np.array([[25, 16]]),
    np.array([[11, 2], [13, 4]]),
    np.array([[7, 81], [5, 6], [11, 12]])
])
print("Concatenated Array:\n", ct_arr)

Concatenated Array:
 [[25 16]
 [11  2]
 [13  4]
 [ 7 81]
 [ 5  6]
 [11 12]]


In [12]:
# Sort 'newArray' in order into 'sortedArray'
sorted_arr = np.sort(ct_arr)
print("Sorted Array:\n", sorted_arr)

Sorted Array:
 [[16 25]
 [ 2 11]
 [ 4 13]
 [ 7 81]
 [ 5  6]
 [11 12]]


In [16]:
# Unpack the array tuples from the above 'reshapedArray' into 4 well named variables. Print the 4 variables.
(x1, x2, x3) = arr[0]
(y1, y2, y3) = arr[1]

print("unpacked array:\n",x1,x2,x3,y1,y2,y3)

unpacked array:
 [0 1] [2 3] [4 5] [6 7] [8 9] [10 11]


In [19]:
# Combined and sort the following arrays into one called 'comboArray' ...
one = ([10, 11, 12, 13, 14, 15, 16, 17])
two = ([20, 21, 22, 23, 24, 25, 26, 27])
three = ([ 0, 1, 2, 3, 4, 5, 6, 7])
comboArray = np.sort(np.concatenate([one, two, three]))
print("comboArray:\n", comboArray)

comboArray:
 [ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]


In [20]:
# Take 'comboArray' and perform the following slicing activities:
# print sec1 - the 2nd element
sec1 = comboArray[1]
print("sec1:",sec1)

# print sec2 - all elements from the 3rd element to the last
sec2 = comboArray[2:]
print("sec2:",sec2)

# print sec3 - all elements from the 4th to the 14th elements
sec3 = comboArray[3:14]
print("sec3:",sec3)

# print sec4 - the last 6 elements
sec4 = comboArray[-6:]
print("sec4:",sec4)

# print sec5 - all element from #0 up to and including #15, using the negative number method, i.e. taking a section from the end.
sec5 = comboArray[:-15:-1]
print("sec5:",sec5)

# print sec6 - from #20 every even element to the end
sec6 = comboArray[20::2]
print("sec6:",sec6)

# print sec7 - from the last element moving forward, every 5th element.
sec7 = comboArray[::-5]
print("sec7:",sec7)

sec1: 1
sec2: [ 2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]
sec3: [ 3  4  5  6  7 10 11 12 13 14 15]
sec4: [22 23 24 25 26 27]
sec5: [27 26 25 24 23 22 21 20 17 16 15 14 13 12]
sec6: [24 26]
sec7: [27 22 15 10  3]


In [22]:
# Using Series, create a DataFrame that looks like this:

# Ingredients	Quantity	Unit
# Flour	4	cups
# Milk	1	cup
# Eggs	2	large
# Spam	1	can
# Name: Dinner, dtype: object
import pandas as pd

dic={
    'Ingredients': ['Flour', 'Milk', 'Eggs', 'Spam'],
    'Quantity': [4, 1, 2, 1],
    'Unit': ['cups', 'cup', 'large', 'can']
}
Dinner = pd.DataFrame(dic)
print("\nDataFrame", Dinner)


DataFrame   Ingredients  Quantity   Unit
0       Flour         4   cups
1        Milk         1    cup
2        Eggs         2  large
3        Spam         1    can


In [23]:
# Take this data and create a DataFrame named studentData
info=    {'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
        'Height': [5.1, 6.2, 5.1, 5.2],
        'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
        'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
        'Age': [21, 23, 24, 21],
        'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
        'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
    }

student_df = pd.DataFrame(info)

In [24]:
# Add a new column to the DataFrame with the following deserts: ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]
student_df['Desserts'] = ["Ice cream", "Cashew Fudge", "Waffles", "Carrot Halwa"]

In [27]:
# Sort the 'studentData' DataFrame in Ascending order -- Sorting by column 'Name' and then "address"
sorted_student = student_df.sort_values(by=['Name', 'address'])
sorted_student

Name  Height Qualification  address  Age        Pets           sport  \
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   

       Desserts  
3  Carrot Halwa  
2       Waffles  
0     Ice cream  
1  Cashew Fudge

In [28]:
# Save this DataFrame here below to disc as a .CSV file with the name cows_and_goats.csv:
df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])
df.to_csv('cows_and_goats.csv', index=True)

In [29]:
# (A) Using Pandas, make your own .CSV file with data on vegetables and save it.
# (B) Using Pandas, make a change to your CSV file, and save a copy with a different name.

vegetables_data = {
    'Vegetable': ['Carrot', 'Broccoli', 'Spinach'],
    'Quantity': [11, 52, 23],
    'Unit': ['lbs', 'lbs', 'lbs']
}
vegetables_df = pd.DataFrame(vegetables_data)
vegetables_df.to_csv('vegetables.csv', index=False)

# (B) Make a change to the CSV file
vegetables_df['Quantity'] += 3
vegetables_df.to_csv('vegetables_updated.csv', index=False)